version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./src:/app/src
      - ./data:/app/data
    command: python ./src/main.py

  test:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.test
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
    command: pytest -v ./tests
